{
 "title": "IoT Supervision Industrielle - Hackathon 2026",
 "tags": [
  "iot",
  "hackathon",
  "supervision",
  "industriel"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vue Globale - Indicateurs Temps Réel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Temp. Salle Serveur",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"salle-serveur\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Humidité Salle Serveur",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"salle-serveur\")\n  |> filter(fn: (r) => r._field == \"humidite\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Vibration Atelier",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"atelier\")\n  |> filter(fn: (r) => r._field == \"vibration\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Temp. Atelier",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"atelier\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Luminosité Local Élec.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"local-electrique\")\n  |> filter(fn: (r) => r._field == \"luminosite\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Temp. Local Élec.",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"local-electrique\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> last()"
    }
   ]
  },
  { "title": "Salle Serveur - Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Temperature Salle Serveur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"salle-serveur\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Humidite Salle Serveur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"salle-serveur\")\n  |> filter(fn: (r) => r._field == \"humidite\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Atelier Technique - Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Vibration Atelier Technique",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"atelier\")\n  |> filter(fn: (r) => r._field == \"vibration\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Temperature Atelier Technique",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"atelier\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Local Electrique - Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Luminosite Local Electrique",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"local-electrique\")\n  |> filter(fn: (r) => r._field == \"luminosite\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Temperature Local Electrique",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"local-electrique\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Gauges - Niveaux Critiques", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Gauge Temp. Salle Serveur",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"salle-serveur\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Gauge Vibration Atelier",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"atelier\")\n  |> filter(fn: (r) => r._field == \"vibration\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Gauge Luminosite Local Elec.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"local-electrique\")\n  |> filter(fn: (r) => r._field == \"luminosite\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Gauge Humidite Salle Serveur",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensors\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"capteurs_industriels\")\n  |> filter(fn: (r) => r.zone == \"salle-serveur\")\n  |> filter(fn: (r) => r._field == \"humidite\")\n  |> last()"
    }
   ]
  }
 ]
}